if (CMAKE_BUILD_TYPE STREQUAL "Release")
  string(APPEND CMAKE_CXX_FLAGS " -Os")
  add_link_options(--js-opts 3)
  add_link_options(--llvm-lto 3)
  add_link_options(--llvm-opts 3)
  add_link_options(--closure 1)
endif()
