if (CMAKE_BUILD_TYPE STREQUAL "Release")
  add_compile_options(-O3)
  add_compile_options(-flto)
  add_compile_options(-g0)
  add_link_options(-O3)
  add_link_options(-flto)
  add_link_options(-g0)
  add_link_options(--closure 1)
endif()
